
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(1,25,1,'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSAV400sLMSOUm8VF5d3L-XMyF82-dWy6qXQe-DLp8IaMsMkqSU');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(2,3,0,'https://an2-img.amz.wtchn.net/image/v2/tMV4xweIwBYwOmYwBwJwvg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk56STVlREV3T0RCeE9EQWlYU3dpY0NJNklpOTJNaTl6ZEc5eVpTOXBiV0ZuWlM4eE5qTXhNek16TkRrek5EY3dORFF5TnpjNEluMC5IQUtCYUVEQ2FsX0FvbHIxU1dMVFdDeC1pbkJWakd0RDZaYXZteHJMYXZF');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(3,4,0,'https://m.media-amazon.com/images/M/MV5BNGM4NGMxNGEtNWExOS00MzkyLTkxYTQtYmExMmYyZTNhZmEyXkEyXkFqcGdeQXVyMTYzMDM0NTU@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(4,22,1,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcRqm-taTL6_aVW31WQ15E4xkOFt4ZbNIoYhYfG0YPq_qoZSx97Q');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(5,23,0,'https://encrypted-tbn2.gstatic.com/images?q=tbn:ANd9GcSKY_oPtE1t6Wgq56I1_Rt1tALBxracEfXYB4iHuzwtnOS7Ka8O');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(6,24,1,'http://t1.daumcdn.net/cfile/116F1B10AB05B5D1DD');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(7,25,1,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcTKYSzCgpHCAO91XEmgB0PcgxYvTw7WcxUdI5K8SAGna334zcuz');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(8,253,1,'https://upload.wikimedia.org/wikipedia/en/9/9c/ComradeX.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(9,251,1,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcTc0SiWCaQ_PNzFF4kEkkk14bmc2aAVcEwKsEYJTXZ_lq_IZBI_');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(10,245,1,'https://m.media-amazon.com/images/M/MV5BMTU1NzkyNjE3MV5BMl5BanBnXkFtZTgwMDM2NTcwMzE@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(11,355,0,'https://encrypted-tbn1.gstatic.com/images?q=tbn:ANd9GcQkOekIQomDtcjgeT9XScp8aV_kYNxkJOr8tgVUDUWK8rKXNvt3');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(12,125,0,'https://an2-img.amz.wtchn.net/image/v2/H69F6V10Q5SmBuMFG802QA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk56STVlREV3T0RCeE9EQWlYU3dpY0NJNklpOTJNaTl6ZEc5eVpTOXBiV0ZuWlM4eE5qTXhNREV5T0RJd09EQTFOak01TnpjMUluMC5abVBxZk4xQW1DTkRHOHdGNFFkY2Zua3UwdkRmSTlScllYT0VOcTdPNjhR');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(13,5,1,'https://encrypted-tbn3.gstatic.com/images?q=tbn:ANd9GcQBawNM5U-gcjf6CbLfQ7rDbg00wHLx4Q5hfgHoKCvzv5rIVJye');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(14,34,1,'https://m.media-amazon.com/images/M/MV5BMjA5MTE1MjQyNV5BMl5BanBnXkFtZTcwODI4NDMwNw@@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(15,85,1,'https://m.media-amazon.com/images/M/MV5BNmMzY2VhYzEtNDdhOC00ZDFjLTk4NjctYjRlYjBjNzE1YzM0XkEyXkFqcGdeQXVyMjI4MjA5MzA@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(16,111,0,'https://m.media-amazon.com/images/M/MV5BYTU5MDVmOWItOTAzYy00NTBlLThmYjktNDA3MWIwYWQ1M2UzXkEyXkFqcGdeQXVyMTQxNzMzNDI@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(17,11,1,'https://asianwiki.com/images/c/c1/Train_Man-_Densha_Otoko1.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(18,55,1,'http://t1.daumcdn.net/movie/f4c8391cb3268696622464036c43bb23fb224569');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(19,55,1,'https://m.media-amazon.com/images/M/MV5BYWI1YWQxNDYtY2IzZS00ZjAwLWE1ZDktOWU3NzQ3MTU4OTBhXkEyXkFqcGdeQXVyMjIyNjE2NA@@._V1_FMjpg_UX1000_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(20,5,1,'https://m.media-amazon.com/images/M/MV5BMTM5MjYyNTQ5MF5BMl5BanBnXkFtZTgwMDM1MzcxMTE@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(21,5,1,'https://m.media-amazon.com/images/M/MV5BMTgxODQ3NTg0Nl5BMl5BanBnXkFtZTcwMTQyMDM1Nw@@._V1_.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(22,1,1,'https://flxt.tmsimg.com/assets/p11668_p_v8_ap.jpg');
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(23,5,1,'https://flxt.tmsimg.com/assets/p13778988_b1t_v9_aa.jpg');

insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(24,25,1,'https://an2-img.amz.wtchn.net/image/v2/pg8YCWar3PD_lxK4U_4dQw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5ERTNPREF6TkRBMU5EWTVNakEyT0RRaWZRLlh4R2RpVWEzdGpjc0wyczFFQUdqRVBGRUlHR3BITTV6dzVSS0RNdHdQVk0');--맛있는 녀석들
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(25,35,1,'https://an2-img.amz.wtchn.net/image/v2/KZnF0OvWN4d1UowLSwF2MA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16TXdOVEU1TlRReU56WTBORE0xTlRZaWZRLkJ2UXN5WEJFTGlZMUJNUnZjUG1MWllzTWNZcnV1WFBUVWJRSWZCOG92SEU');--하코즈메 ~싸워라!
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(26,33,0,'https://an2-img.amz.wtchn.net/image/v2/P1xI5xbxmwfZ01R1ver6pw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5UZ3lNak0yTURRd09UTTVNRGsxTlRRaWZRLjNoakpsa1UtVHhrWmVpQXBUaXZjVkJtVlozc0xadjYwbzBUQmp3Nk44cm8');--경쟁의 파수꾼
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(27,22,0,'https://an2-img.amz.wtchn.net/image/v2/mde28xC0l4gWJg0VnY3xIg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5qRTNNemd5TVRVM016Y3lNVEUwTnpJaWZRLnNuWnZqNkQxLWtaU3pzcmZ2bG01RUkyQklfb3VVXzBIM2hIUXVSMDZuVFk');--첫사랑의 악마
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(28,64,1,'https://an2-img.amz.wtchn.net/image/v2/KLAzuPAxj3kMmvRzY_wVQg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16TXdOVGsyTWpVMk5qWXlNVFl6TURZaWZRLnVEZjRWWU9VWEtOdVZjU0JtRHVVelBJZU1ERGhsYTZwX3lDTE1IT1NfTU0');--콩트가 시작된다
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(29,34,0,'https://an2-img.amz.wtchn.net/image/v2/qGx7ja9x-8oM-S8bw9NbeQ.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16RTFNalkyTkRNeE1UQTFPVGd4TXpJaWZRLlBuaUM3dWJFcFFmb3JOMHNnOU1HdWlranQ5ZjdockYxbFlVbmhFZm0zNEU');--천고결진
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(30,54,1,'https://an2-img.amz.wtchn.net/image/v2/6syW7yZcJhZzPTXSElr1Aw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16WXpOakV4T1RFME9ESTBPREkxTlRraWZRLktNNUlvb0dmeWR1dFgxMEhlZTdIeWVSS3dhbUlmbEJ5S281Zm1TVG9fdms');--@계정을 삭제하였습니다
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(31,355,0,'https://an2-img.amz.wtchn.net/image/v2/1lb5lceMiOzASKWg9m-CuA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16azNNVEE1TURNMk5UVTFPRFkyTXpVaWZRLm1qUjlaSVNxSElZV0twYVVSSGZhOG1yYjg4b0FyMkItS3pieHVacXh1T28');--니시아적영요: 너
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(32,77,1,'https://an2-img.amz.wtchn.net/image/v2/J3y613t3Yd24Lu1Q06IXHw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5UYzJOems1TURZMk9EWTNPVFU1TWpRaWZRLklaQ3VGcVlHV0JrZ0ZFSEVCbWZGNWE0aXRwUEc0cDNVZ002V05oN3RySWM');--스파이 패밀리
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(33,26,0,'https://an2-img.amz.wtchn.net/image/v2/zTmLhrziS6ACyYFkeLEwzw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16UXlNREk0TXpRM016Z3lPVEF4TlRFaWZRLmNwRGd3UXlsSi1pbFVkMGxGajJQSXFocDVrWE1wUXBzWUY1NmZMVU5YTXM');--오분순삭: 무한도전
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(34,99,0,'https://an2-img.amz.wtchn.net/image/v2/393GTN8BvOBkUTbADuReFQ.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5qVXhNamsxTlRjNU5EQTNOamszTlRZaWZRLl80TWI2SElialh1UEhCZXk3YXVpTFhVYUlGMEE5OHdoZWpOUElydDAyWTg');--체인소 맨
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(35,34,1,'https://an2-img.amz.wtchn.net/image/v2/sFrm4qrIeU1eBwNaUbBkYA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5qZ3hORFEzTnpnMk1EQTROVGd6TWpBaWZRLktCM2Vhc29Ya0ZKUHBQZXJ6bVVpN3N4S25iOUhHVEhHSVlaeEdQT181Y3M');--사일런트
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(36,35,1,'https://an2-img.amz.wtchn.net/image/v2/T5V5ZHlfyiR8rGw5ddNCAw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5qazFNemt5TlRnM01ETXlORGs0TVRjaWZRLkRsTXdwUlZ2aGZqVUY4ZFlQa1pRWmVNUWxsS0FhVURlTWxXMm9vOVpTUVk');--오늘은 좀 매울지도 몰라
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(37,125,0,'https://an2-img.amz.wtchn.net/image/v2/YcgrTrqPuZnNJPFSBOw5Jg.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5qZ3hOVGMwTkRJd05USTJNVGs1TkRRaWZRLlZkRjRHYXM1ZEE5X1NGQjE1V1Y3YVFzWl9JSXV4QWo4eC1SWnVra3g1ME0');--SPEC(스펙)
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(38,53,0,'https://an2-img.amz.wtchn.net/image/v2/Su7ZNT9tkWAMJb0T8u29fw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5UTTVOalF6TnpNeU56TXhOVE0zTmpRaWZRLkppcHVCSXlRdnVTNFZJU1Z3emxjTG5ocEtEZ1BhMmtSSjladnNRbFpuX0U');--나혼자산다
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(39,64,0,'https://an2-img.amz.wtchn.net/image/v2/jKEahy3NwWMLTDj_A5JO3w.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5qWTNOelExT0RJek9UY3dNVEl5TXpraWZRLjdwaHRsOTJMUnRRUlN2Zk1ubUkzeU81czY3cE1UNXRiSGhsX2laTnBjOGM');--너의 꽃이 될래
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(40,44,1,'https://an2-img.amz.wtchn.net/image/v2/3jr6xiKA7PzPP03-I50FTw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk16RXdNVFF6TWprMU9UTXhNRE13T0RVaWZRLk5BanU1dTdOYXZiVC1UcFRCY25aQ1JGOG5oc2F1TG80cUhlWVYwUFdSSmM');--그것이 알고싶다
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(41,24,0,'https://an2-img.amz.wtchn.net/image/v2/uNSUAmnzFymCu4aq79p0xA.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5UUTFPVEkwT0RFeU1UVXdNekExT1RnaWZRLnR5cE5FbjQ0LVVUYkNkWUR4S1h3TVBZeFdubTJ3YWdoNWFhQ1l5ODJCemM');--놀면 뭐하니?
insert into movie_data_extended(movie_id, hit, exclusive_movie,movie_image) values(42,44,0,'https://an2-img.amz.wtchn.net/image/v2/KoOXpb4hk59ahb7q44YTqw.jpg?jwt=ZXlKaGJHY2lPaUpJVXpJMU5pSjkuZXlKdmNIUnpJanBiSW1SZk5ETXllRFkwTUhFNE1DSmRMQ0p3SWpvaUwzWXlMM04wYjNKbEwybHRZV2RsTHpFMk5ETTRPREEwTURBNU5qTTBORGszT0RFaWZRLklVUDROdEduWlNCS3NrbGRfOFItenF4cWItM2ptcWpRQ0xQTUVRMGozZVk');--연애의 참견

commit;


