/*user table settings*/
--DROP TABLE user_data PURGE;
CREATE TABLE user_data(
    user_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    name VARCHAR2(50) NOT NULL,
    email VARCHAR2(50) NOT NULL,
    password VARCHAR2(50) NOT NULL,
    age_restriction CHAR(1) CONSTRAINT user_data_age_restriction_ck
        CHECK(age_restriction = '0' OR age_restriction = '1'),
    marketing_agreement CHAR(1) CONSTRAINT user_data_marketing_agreement_ck
        CHECK(marketing_agreement = '0' OR marketing_agreement = '1'),
    logtime DATE DEFAULT sysdate,
    CONSTRAINT user_data_unique UNIQUE (email)
);
--make user_id identity restart
--ALTER TABLE user_data MODIFY(user_id GENERATED AS IDENTITY (START WITH 1));

--DROP TABLE user_membership;
CREATE TABLE user_membership(
    user_id INT,
    user_membership_type VARCHAR2(50),
    user_membership_start_date VARCHAR2(50)
);



/*movie table settings*/
--DROP TABLE movie_data PURGE;
CREATE TABLE movie_data(
    movie_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    movie_title VARCHAR2(150) NOT NULL,
    movie_age_restriction SMALLINT NOT NULL,
    movie_release_date DATE NOT NULL,
    movie_time SMALLINT NOT NULL,
    content_type VARCHAR2(50) NOT NULL
);

--DROP TABLE movie_rating PURGE;
CREATE TABLE movie_rating(
    movie_id INT NOT NULL,
    review_id INT NOT NULL
);

--DROP TABLE movie_reviewer PURGE;
CREATE TABLE movie_reviewer(
    review_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    user_id INT NOT NULL, --name join also don't let access multiple value in each movie title
    review_description VARCHAR2(255) NOT NULL,
    rating_star SMALLINT NOT NULL
);

--DROP TABLE movie_cast PURGE;
CREATE TABLE movie_cast(
    movie_id INT NOT NULL,
    actor_id INT NOT NULL
);

--DROP TABLE movie_genre PURGE;
CREATE TABLE movie_genre(
    movie_id INT NOT NULL,
    genre_id INT NOT NULL
);

--DROP TABLE movie_tag PURGE;
CREATE TABLE movie_tag(
    movie_id INT NOT NULL,
    tag_id INT NOT NULL
);

--DROP TABLE actor PURGE;
CREATE TABLE actor(
    actor_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    actor_fname VARCHAR2(50),
    actor_lname VARCHAR2(50)
);

--DROP TABLE genre PURGE;
CREATE TABLE genre(
    genre_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    genre_title VARCHAR2(50) NOT NULL,
    CONSTRAINT genre_unique UNIQUE (genre_title)
);

--DROP TABLE tag PURGE;
CREATE TABLE tag(
    tag_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    tag_title VARCHAR2(50) NOT NULL,
    CONSTRAINT tag_unique UNIQUE (tag_title)
);



/*search page settings*/
--DROP TABLE search_title PURGE;
CREATE TABLE search_title(
    video_genre VARCHAR2(50),
    webtoon_genre VARCHAR2(50),
    video_nation VARCHAR2(50)
);
INSERT INTO search_title VALUES('판타지','판타지','한국');
INSERT INTO search_title VALUES('코미디','코미디','중국');
INSERT INTO search_title VALUES('한국 드라마','미스터리','미국');
INSERT INTO search_title VALUES('미국 드라마','공포','이탈리아');
INSERT INTO search_title VALUES('로맨스','로맨스','인도');
INSERT INTO search_title VALUES('액션','액선','필리핀');
INSERT INTO search_title VALUES('애니메이션','','');
INSERT INTO search_title VALUES('음악','','');
INSERT INTO search_title VALUES('블록버스터','','');
INSERT INTO search_title VALUES('공포','','');

--홍헌 테이블 추가
--비디오 페이지
--drop table movie_data_extended purge;
create table movie_data_extended(
movie_id NUMBER(38,0),
hit number,
exclusive_movie number,
movie_image varchar2(4000)
);

create table movie_banner(
bannerTitle varchar2(200),
bannerExpression varchar2(200),
bannerExplain varchar2(200),
bannerImage varchar2(4000)
);

--웹툰
--drop table webtoon_contents purge;
create table webtoon_contents(
webtoon_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
webtoonTitle varchar2(100),
webtoonImage varchar2(4000),
ageRestriction number default 0 not NULL,
hit number default 0 not null,
exclusive_contents number(1)
);

--drop table webtoon_genre purge;
create table webtoon_genre(
webtoon_id int,
genre_id number
);

--drop table webtoon_genre_number purge;
create table webtoon_genre_number(
genre_id int GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
genre_title varchar2(30) not null,
CONSTRAINT genre_type UNIQUE (genre_title)
);

commit;
