insert into tag (tag_title) values ('판타지');
insert into tag (tag_title) values ('코미디');
insert into tag (tag_title) values ('한국 드라마');
insert into tag (tag_title) values ('미국 드라마');
insert into tag (tag_title) values ('로맨스');
insert into tag (tag_title) values ('액션');
insert into tag (tag_title) values ('애니메이션');
insert into tag (tag_title) values ('음악');
insert into tag (tag_title) values ('블록버스터');
insert into tag (tag_title) values ('공포');
insert into tag (tag_title) values ('미스터리');
insert into tag (tag_title) values ('한국');
insert into tag (tag_title) values ('중국');
insert into tag (tag_title) values ('미국');
insert into tag (tag_title) values ('이탈리아');
insert into tag (tag_title) values ('인도');
insert into tag (tag_title) values ('필리핀');