--DROP TABLE user_card PURGE;
create table user_card(
    user_id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 1) NOT NULL PRIMARY KEY,
    email VARCHAR2(50) NOT NULL,
    card_Number VARCHAR2(30),
    card_Expiry VARCHAR2(10),
    card_Birth NUMBER,
    logtime DATE DEFAULT sysdate
--  CONSTRAINT user_card_unique UNIQUE (email)
);